services:
  sqlyzr:
    build:
      context: .
      dockerfile: e2e.Dockerfile
    restart: no
    env_file: .env.e2e.docker.local
    volumes:
      - "./data:/app/data"
      - "./e2e.py:/app/e2e.py"
      - "./e2e.json:/app/e2e.json"
    entrypoint: "python e2e.py"
    shm_size: '16gb'
    networks:
      - sqlyzr
  mockserver:
    build:
      context: .
      dockerfile: e2e.Dockerfile
    restart: no
    env_file: .env.e2e.docker.local
    volumes:
      - "./data:/app/data"
      - "./e2e.py:/app/e2e.py"
      - "./e2e.json:/app/e2e.json"
    entrypoint: "python src/mock_server/mock_http_server.py"
    shm_size: '16gb'
    networks:
      - sqlyzr
  mysql:
    image: mysql:8.0
    restart: on-failure
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_ROOT_PASSWORD=sheep
    volumes:
      - "./confs/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./data/beaver/dumps:/docker-entrypoint-initdb.d"
      - "./data/beaver:/beaver"
      - "./data/beaver_data:/var/lib/mysql"
    networks:
      - sqlyzr

networks:
  sqlyzr:
