version: '3'

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
      args:
        - "WEB_PORT=${WEB_PORT}"
        - "WEB_DOMAIN=${WEB_DOMAIN}"
    env_file: .env
    volumes:
      - /data:/app/data
      - ./gui.json:/app/gui.json
    network_mode: host
