services:
  web:
    image: "${IMAGE_TAG}"
    volumes:
      - "/data/web_out:/app/out"
      - "/data:/app/data"
      - "./gui.json:/app/gui.json"
      - "./.env:/app/.env"
    environment:
      RUNNER_TRACKING_ID: ""
    env_file: ".env"
    expose:
      - "${SQLYZR_WEB_PORT}"
    networks:
      - sqlyzr
    shm_size: '16gb'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.tls=true"
      - "traefik.http.routers.ui.rule=Host(`ui.${SQLYZR_DOMAIN}`)"

  mysql:
    image: mysql:8.0
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_ROOT_PASSWORD=sheep
    volumes:
      - "./confs/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "/data/beaver/dumps:/docker-entrypoint-initdb.d"
      - "/data/beaver:/beaver"
      - "/data/beaver_data:/var/lib/mysql"
    networks:
      - sqlyzr
  traefik:
    image: traefik:v2.11
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.tls.yml:/etc/traefik/dynamic/tls.yml
      - /certs:/certs
    networks:
      - sqlyzr
  whoami:
    image: traefik/whoami
    networks:
      - sqlyzr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${SQLYZR_DOMAIN}`)"

volumes:
  web_out:

networks:
  sqlyzr:
