version: '3.8'

services:
  web:
    image: "${IMAGE_TAG}"
    volumes:
      - "web_out:/app/out"
      - "/data:/app/data"
      - "./gui.json:/app/gui.json"
    environment:
      - "MYSQL_HOST=mysql"
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    networks:
      - sqlyzr

volumes:
  web_out:

networks:
  sqlyzr:
    external: true
