version: '3'

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
      args:
        - "WEB_PORT=${WEB_PORT}"
        - "WEB_DOMAIN=${WEB_DOMAIN}"
    volumes:
      - ./data:/app/data
      - ./gui.json:/app/gui.json
    environment:
      - "WEB_PORT=${WEB_PORT}"
    network_mode: host
