services:
  sqlyzr:
    build:
      context: .
      tags:
        - "${SQLYZR_IMAGE}"
      args:
        SQLYZR_WEB_PORT: "${SQLYZR_WEB_PORT:?SQLYZR_WEB_PORT}"
        SQLYZR_API_URL: "${SQLYZR_API_URL:?SQLYZR_API_URL}"
    volumes:
      - "./data:/app/data"
      - "./gui.json:/app/gui.json"
      - "./out:/app/out"
      - "./confs:/app/confs"
    ports:
      - "${SQLYZR_WEB_PORT}:${SQLYZR_WEB_PORT}"
    env_file: ".env.docker"
    networks:
      - sqlyzr
    shm_size: '8gb'

  mysql:
    image: mysql:8.0
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_ROOT_PASSWORD=sheep
    volumes:
      - "./confs/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./data/beaver/dumps:/docker-entrypoint-initdb.d"
      - "./data/beaver:/beaver"
      - "./data/beaver_data:/var/lib/mysql"
    networks:
      - sqlyzr

networks:
  sqlyzr:
