services:
  sqlyzr:
    build: .
    restart: no
    environment:
      - "OPENAI_API_KEY=sk-proj"
      - "OPENAI_GROUP_ID=org"
      - "OPENAI_PROJ_ID=proj"
      - "OPENAI_USAGE_TIER=tier5"
      - "OPENAI_BASE_URL=http://localhost:8888"
      - "DAIL_CACHE_DIR=data"
      - "SQLYZR_DEVICE=cpu"
      - "DB_TIMEOUT=60000"
      - "DB_CACHE=0"
      - "GPT_CACHE=0"
      - "NUM_PROC_CHUNKS=6"
      - "NUM_PROCS=6"
      - "ENC_PROG=1"
      - "ASYNC_BATCH=20"
      - "PYTHONUNBUFFERED=1"
      - "MYSQL_HOST=localhost"
    volumes:
      - "/data:/app/data"
      - "./e2e.py:/app/e2e.py"
      - "./e2e.json:/app/e2e.json"
    entrypoint: "python e2e.py"
    network_mode: host
    shm_size: '8gb'
