SELECT_CLAUSE_TEMPLATE = "SELECT {} FROM t"
FROM_CLAUSE_TEMPLATE = "SELECT a FROM {}"
WHERE_CLAUSE_TEMPLATE = "SELECT a FROM b WHERE {}"
GROUP_BY_CLAUSE_TEMPATE = "SELECT a FROM b GROUP BY {}"
ORDER_BY_CLAUSE_TEMPATE = "SELECT a FROM b ORDER BY {}"

TEST_SQLS = [
    SELECT_CLAUSE_TEMPLATE.format("column"),
    SELECT_CLAUSE_TEMPLATE.format("table.column"),
    SELECT_CLAUSE_TEMPLATE.format("(SELECT a FROM b)"),
    SELECT_CLAUSE_TEMPLATE.format("a + b"),
    SELECT_CLAUSE_TEMPLATE.format("'str'"),
    SELECT_CLAUSE_TEMPLATE.format("12"),
    SELECT_CLAUSE_TEMPLATE.format("12.34"),
    SELECT_CLAUSE_TEMPLATE.format("x + y"),
    SELECT_CLAUSE_TEMPLATE.format("x NOT LIKE y"),
    SELECT_CLAUSE_TEMPLATE.format("x IN (SELECT a FROM b)"),
    SELECT_CLAUSE_TEMPLATE.format("x NOT IN (SELECT a FROM b)"),
    SELECT_CLAUSE_TEMPLATE.format("COUNT(c)"),
    SELECT_CLAUSE_TEMPLATE.format("COUNT(DISTINCT c)"),
    SELECT_CLAUSE_TEMPLATE.format("c BETWEEN x AND y"),
    SELECT_CLAUSE_TEMPLATE.format("c as a1"),
    SELECT_CLAUSE_TEMPLATE.format("DISTINCT c"),
    SELECT_CLAUSE_TEMPLATE.format("c1, c2"),
    SELECT_CLAUSE_TEMPLATE.format("EXISTS (SELECT a FROM b)"),
    SELECT_CLAUSE_TEMPLATE.format("NOT EXISTS (SELECT a FROM b)"),
    FROM_CLAUSE_TEMPLATE.format("t1"),
    FROM_CLAUSE_TEMPLATE.format("t1 AS t2"),
    FROM_CLAUSE_TEMPLATE.format("(SELECT b FROM c)"),
    FROM_CLAUSE_TEMPLATE.format("(SELECT b FROM c) AS t1"),
    FROM_CLAUSE_TEMPLATE.format("t1, t2"),
    FROM_CLAUSE_TEMPLATE.format("t1 JOIN t2"),
    FROM_CLAUSE_TEMPLATE.format("t1 JOIN t2 ON x = y"),
    FROM_CLAUSE_TEMPLATE.format("t1 JOIN t2 JOIN t3"),
    FROM_CLAUSE_TEMPLATE.format("t1 JOIN t2 ON x = y JOIN t3 ON y = z"),
    GROUP_BY_CLAUSE_TEMPATE.format("c"),
    GROUP_BY_CLAUSE_TEMPATE.format("c1, c2"),
    GROUP_BY_CLAUSE_TEMPATE.format("c1, c2 HAVING x > 2"),
    ORDER_BY_CLAUSE_TEMPATE.format("c"),
    ORDER_BY_CLAUSE_TEMPATE.format("c ASC"),
    ORDER_BY_CLAUSE_TEMPATE.format("c1, c2"),
    WHERE_CLAUSE_TEMPLATE.format("x > 2"),
    "SELECT a FROM b UNION SELECT c FROM d",
    "SELECT a FROM b LIMIT 5"
]
