name: Deploy to Staging

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  COMPOSE_PROJECT_NAME: staging

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: staging
      url: https://ui.${{vars.SQLYZR_DOMAIN}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

      - name: Deploy
        run: echo "IMAGE_TAG=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV

      - name: Create .env
        env: ${{ vars }}
        run: |
          env > .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Print env
        run: cat .env

      - name: Docker compose up
        env: ${{ vars }}
        run: |
          docker compose -f docker-compose.staging.yml down -v
          sleep 3
          docker compose -f docker-compose.staging.yml pull
          docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_TAG
          docker compose -f docker-compose.staging.yml up --force-recreate -d

      - name: Logs
        env: ${{ vars }}
        run: docker compose -f docker-compose.staging.yml logs

      - name: Health check
        env: ${{ vars }}
        run: |
          for i in {1..10}; do
            if curl -fs https:///ui.$SQLYZR_DOMAIN/api/health; then
              echo "Server is up"
              exit 0
            fi
            echo "Waiting for server..."
            sleep 1
          done
          echo "Health check failed"
          exit 1

      - name: Cleanup on failure
        if: failure()
        run: docker compose -f docker-compose.staging.yml down -v
