name: Deploy to Staging

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed
#  push:
#    branches:
#      - demo
#    paths:
#      #      - 'src/**'
#      #      - 'tests/**'
#      #      - Dockerfile
#      #      - pyproject.toml
#      - docker-compose.staging.yml
#      - .github/workflows/deploy.yml
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  COMPOSE_PROJECT_NAME: staging

jobs:
  deploy:
    runs-on: [ self-hosted, cd ]
    environment:
      name: staging
      url: https://temp.${{vars.SQLYZR_DOMAIN}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image Tag
        run: |
          echo "SQLYZR_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV
          # Note: short SHA usually works, but full head_sha is safest for mapping

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

      - name: Deploy
        run: echo "SQLYZR_IMAGE=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV

      - name: Create .env
        run: |
          echo "DB_CACHE=${{ vars.DB_CACHE }}" >> .env
          echo "GPT_CACHE=${{ vars.GPT_CACHE }}" >> .env
          echo "ENC_PROG=${{ vars.ENC_PROG }}" >> .env
          echo "PYTHONUNBUFFERED=${{ vars.PYTHONUNBUFFERED }}" >> .env
          echo "NUM_PROCS=${{ vars.NUM_PROCS }}" >> .env
          echo "NUM_PROC_CHUNKS=${{ vars.NUM_PROC_CHUNKS }}" >> .env
          echo "ASYNC_BATCH=${{ vars.ASYNC_BATCH }}" >> .env
          echo "DB_TIMEOUT=${{ vars.DB_TIMEOUT }}" >> .env
          echo "SQLYZR_DEVICE=${{ vars.SQLYZR_DEVICE }}" >> .env
          echo "DAIL_CACHE_DIR=${{ vars.DAIL_CACHE_DIR }}" >> .env
          echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}" >> .env
          echo "MYSQL_HOST=${{ vars.MYSQL_HOST }}" >> .env
          echo "SQLYZR_DOMAIN=${{ vars.SQLYZR_DOMAIN }}" >> .env
          echo "SQLYZR_WEB_PORT=${{ vars.SQLYZR_WEB_PORT }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Print env
        run: cat .env

      - name: Copy Data
        run: |
          mkdir -p ./data && cp -r ./sample_data/. ./data/

      - name: Docker compose up
        env: ${{ vars }}
        run: |
          docker compose -f docker-compose.staging.yml down -v
          sleep 3
          docker pull $SQLYZR_IMAGE
          docker inspect --format='{{index .RepoDigests 0}}' $SQLYZR_IMAGE
          docker compose -f docker-compose.staging.yml up --force-recreate -d


      - name: Health check
        env: ${{ vars }}
        run: |
          for i in {1..10}; do
            if curl -fs https:///temp.$SQLYZR_DOMAIN/api/health; then
              echo "Server is up"
              exit 0
            fi
            echo "Waiting for server..."
            sleep 6
          done
          echo "Health check failed"
          exit 1

      - name: Logs
        env: ${{ vars }}
        run: docker compose -f docker-compose.staging.yml logs

      - name: Cleanup on failure
        if: failure()
        run: docker compose -f docker-compose.staging.yml down -v
