name: e2e

on:
  push:
    branches:
      - none
    paths:
      - 'src/**'
      - e2e.Dockerfile
      - requirements.txt
      - docker-compose.e2e.yml
      - e2e.py
      - e2e.json
      - .github/workflows/e2e-runner.yml
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  COMPOSE_PROJECT_NAME: e2e

jobs:
  e2e-test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create .env
        env:
          OPENAI_API_KEY: sk-proj
          OPENAI_GROUP_ID: org
          OPENAI_PROJ_ID: proj
          OPENAI_USAGE_TIER: tier5
          OPENAI_BASE_URL: http://localhost:8888
          DAIL_CACHE_DIR: data
          OPENAI_TIMEOUT: 5
          SQLYZR_DEVICE: cpu
          DB_TIMEOUT: 6000
          DB_CACHE: 1
          GPT_CACHE: 0
          LOG_LEVEL: DEBUG
          NUM_PROC_CHUNKS: 1
          NUM_PROCS: 1
          ENC_PROG: 1
          ASYNC_BATCH: 5
          PYTHONUNBUFFERED: 1
          FORCE: 0
          MYSQL_HOST: mysql
        run: |
          env > .env.e2e
      - name: Print env
        run: cat .env.e2e
      - name: Run E2E tests
        run: |
          docker compose -f docker-compose.e2e.yml up --force-recreate --exit-code-from sqlyzr
      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.e2e.runner.yml rm -f -v

