name: e2e
on:
  push:
    branches: [ synths ]
  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      #
      - name: Run E2E tests
        run: |
          docker compose -f docker-compose.e2e.runner.yml up --build --exit-code-from sqlyzr